### ISSUE TITLE
[Alameda] Nova by Alameda Community Health Care Services - Listing Only 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#251]
Listing Spreadsheet: 
https://docs.google.com/spreadsheets/d/1f8usLKRfbYSIsx-h0brDS9SZZ4LwQy4DdkSQaD5Xmro/edit#gid=1787912937

Additional Details 
* This listing will not use our digital application 
* Instead, we want to replace the application section with something like this below 
* This could be a new component (title, CTA, description text) 
* We also want to hide the What to Expect section, might need to add logic to do that 
![image](https://user-images.githubusercontent.com/3453407/115076683-e8212200-9eca-11eb-979c-43c1f264bed2.png)

For reference here are all the possible application sections we'll want to make sure is not present 
![image](https://user-images.githubusercontent.com/3453407/115076872-2b7b9080-9ecb-11eb-9d03-f6380933157c.png)

**Comment by kathyccheng** [comment]
@slowbot can you mock up what the application section here should look like, where the phone number is the call to action

**Comment by emilyjablonski** [comment]
@software-project Quick question (just knowing that you've adding a lot of our listings) - do you have recommendations for how we'd go about hiding the application fields? Do you think we need a new field on the application or can we use an existing field?

**Comment by software-project** [comment]
@emilyjablonski regarding hiding application section I suppose we should work the way around ApplicationConfig. I'm not sure what happens if we don't add an application method, that controls application section. @jaredcwhite would know more about that. Regarding what to expect section, right now that field is not filled out we would default to county specific text. If this behavior is just a 'one off' I would accept a monkey patch that we used in the past, so use `null` for defaulting to county text, empty string for hiding it and 'full sting' for overriding. If we expect to hide more sections if future, we would need more permanent solution. Maybe application config could also handle that. If not add a json filed that would control visibility of sections.

**Comment by kathyccheng** [comment]
I feel like monkey patch solution for What to Expect should be okay for now, we should clean it up when we get to listings mgmt
