### ISSUE TITLE
Next JS follow on - contextual axios instance with translation headers and county headers 

### ISSUE THREAD

**Issue by kathyccheng** [housingbayarea/bloom#287]
@seanmalbert can you add in details here

**Comment by seanmalbert** [comment]
This issue is either part of or a follow up to creating and using an axios instance for the public app. There are a number of individual/direct axios instances/calls coming out of the updates to the public site (e.g. see pages/listing.tsx) that should be updated to use a single client like the partner's app currently does.

For some more context there are these conversations from other issues:
https://github.com/bloom-housing/bloom/pull/1190#discussion_r630171371
https://github.com/bloom-housing/bloom/pull/1087#discussion_r626205391

Rather than have separate clients for public and partners, we can create one for both to utilize. If a site, let's say partners, doesn't require one or both of the headers, then they can be optional.

@software-project has been a proponent of this, is there any information or thoughts you'd like to add?
