### ISSUE TITLE
Create listing migration script for SMC

### ISSUE THREAD

**Issue by sarahlazarich** [housingbayarea/bloom#715]
Investigate what the script to migrate all 
- AMI Charts
- Preferences
- Programs
- Community Types
- Addresses 
- Listing data

From SMC to Doorway in advance of their transition. 

NOTES:
- All images and file uploads (e.g lottery results) will not be carried over and will have to be done manually in the Doorway environment

**Comment by ludtkemorgan** [comment]
This has been tested in the Doorway dev environment by pulling over the HBA staging SMC listings and data. I will do the same for Doorway staging.

Notes:
- The data in dev environment disappears frequently because every merge does a reseed. When this is run in staging it will persist.
- Not all of the data is transferred as HBA staging has a decent amount of listings using AMI charts and preferences tied to a different jurisdiction. The logs output which ones are not carried over and we will take note of that when we run it in production so we can manually add things if necessary.
