### ISSUE TITLE
Create Alameda County - Chestnut Square Family Listing - Developer: MidPen

### ISSUE THREAD

**Issue by antonelitum** [housingbayarea/bloom#75]
The developer wants this listing to be posted ASAP, they forgot to let us know before.

Here is the spreadsheet 
https://docs.google.com/spreadsheets/d/1U2l4ZJLTM-zgXnwLJj2AigiTgx7dMkuFa2GbLrg3jYU/edit#gid=56577888

**Comment by bk3c** [comment]
I must be missing something, since the spreadsheet looks almost entirely blank at this point (doesn't even include the property name, address, or any relevant dates). Assigning back to @antonelitum until it's a little more fleshed out (or feel free to clue me in if I'm not seeing it).

@pbn4 - heads up that I'm planning on sending this your way once the information is filled in enough to get started.

**Comment by pbn4** [comment]
@pbn OK

**Comment by antonelitum** [comment]
@bk3c that's correct, sorry Ben for not clarifying it before, the developer will be completing it this week we wanted to give you heads up

**Comment by bk3c** [comment]
@antonelitum, @vubang228 checking back in on this listing to see if we expect to have to work on it in the next 2-3 weeks, or if we're still doing it at all? It looks like [maybe we're already past the deadline](https://www.midpen-housing.org/leaseup/chestnutsqrfamily/Chestnut_Family_DRAFT_Marketing_Flyer-FINAL.PDF).

Happy to do whatever if this is a priority, but also want to close it out if we're not expecting it anymore.

**Comment by vubang228** [comment]
@bk3c they haven't responded to 3 emails, but yes please close out since we're well past due.
